name: moments_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^4.5.0
  json_annotation: ^4.6.0
  rxdart: ^0.27.5
  timeago: ^3.2.2
  uuid: ^3.0.6
  email_validator: ^2.1.17
  textfield_tags: ^2.0.2
  device_preview: ^1.1.0
  permission_handler: ^10.0.2
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.5
  extended_image: ^6.3.1
  menu_button: ^1.4.2+1
  flutter_spinkit: ^5.1.0


dev_dependencies:
  build_runner: null

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2

flutter:

  uses-material-design: true
  assets:
    - assets/svg/vectors/
    - assets/svg/sign_in/
    
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf